production:
  environment: production
  company_auth_token: rVAfNGdvfh6va61nDv11

development:
  environment: development
  company_auth_token: rVAfNGdvfh6va61nDv11

test:
  environment: test
  company_auth_token: rVAfNGdvfh6va61nDv11
