# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

admin = FactoryBot.create(:admin)
admin2 = FactoryBot.create(:admin)

client = FactoryBot.create(:client)
client2 = FactoryBot.create(:client)
client3 = FactoryBot.create(:client)

client_profile = FactoryBot.create(:client_profile, :with_photo, client: client)
client_profile2 = FactoryBot.create(:client_profile, client: client2)

streamer = FactoryBot.create(:streamer)
streamer2 = FactoryBot.create(:streamer)
streamer3 = FactoryBot.create(:streamer)

streamer_profile = FactoryBot.create(:streamer_profile, :with_photo, streamer: streamer)
streamer_profile2 = FactoryBot.create(:streamer_profile, streamer: streamer2)

video = FactoryBot.create(:video, streamer: streamer)
video2 = FactoryBot.create(:video, streamer: streamer2)
video3 = FactoryBot.create(:video, streamer: streamer3)

action = GameCategory.create!({ name: 'Ação', admin: admin })
arcade_rhythm = GameCategory.create!({ name: 'Arcade e Ritmo', admin: admin })
fighting = GameCategory.create!({ name: 'Luta e Artes Marciais', admin: admin })
infinite_platform_races = GameCategory.create!({ name: 'Plataformas e Corridas Intermináveis', admin: admin })
hardcore_fighting = GameCategory.create!({ name: 'Porradaria', admin: admin })
action_roguelike = GameCategory.create!({ name: 'Roguelike de Ação', admin: admin })
tps = GameCategory.create!({ name: 'Tiro em Terceira Pessoa', admin: admin })
fps = GameCategory.create!({ name: 'Tiro em primeira pessoa (FPS)', admin: admin })
adventure_casual = GameCategory.create!({ name: 'Aventura e Casual', admin: admin })
adventure = GameCategory.create!({ name: 'Aventura', admin: admin })
casual = GameCategory.create!({ name: 'Casuais', admin: admin })
metroidvania = GameCategory.create!({ name: 'Metroidvania', admin: admin })
puzzle = GameCategory.create!({ name: 'Quebra-Cabeça', admin: admin })
adventure_rpg = GameCategory.create!({ name: 'RPGs de Aventura', admin: admin })
visual_novel = GameCategory.create!({ name: 'Romance Visual', admin: admin })
exceptional_plot = GameCategory.create!({ name: 'Trama Excepcional', admin: admin })
rpg = GameCategory.create!({ name: 'RPG', admin: admin })
jrpg = GameCategory.create!({ name: 'JRPG', admin: admin })
action_rpg = GameCategory.create!({ name: 'RPG de Ação', admin: admin })
strategy_rpg = GameCategory.create!({ name: 'RPG de Estratégia', admin: admin })
rpg_in_groups = GameCategory.create!({ name: 'RPGs em Grupos', admin: admin })
rpg_in_turns = GameCategory.create!({ name: 'RPGs em Turnos', admin: admin })
roguelike = GameCategory.create!({ name: 'Roguelike', admin: admin })
simulator = GameCategory.create!({ name: 'Simulador', admin: admin })
construction_automation = GameCategory.create!({ name: 'Construção e Automação', admin: admin })
dating_simulator = GameCategory.create!({ name: 'Encontros', admin: admin })
space_aviation = GameCategory.create!({ name: 'Espaço e Aviação', admin: admin })
physics = GameCategory.create!({ name: 'Física e "Faça o que quiser"', admin: admin })
business = GameCategory.create!({ name: 'Gestão de Negócios', admin: admin })
rural_manufacturing = GameCategory.create!({ name: 'Rurais e de Fabricação', admin: admin })
life_immersive = GameCategory.create!({ name: 'Vida e Imersivos', admin: admin })
strategy = GameCategory.create!({ name: 'Estratégia', admin: admin })
city_colonies = GameCategory.create!({ name: 'Cidades e Colônias', admin: admin })
tower_defense = GameCategory.create!({ name: 'Defesa de Torres', admin: admin })
strategy_in_turns = GameCategory.create!({ name: 'Estratégia Baseada em Turnos', admin: admin })
rts = GameCategory.create!({ name: 'Estratégia em Tempo Real (RTS)', admin: admin })
four_x = GameCategory.create!({ name: 'Grande Estratégia e 4X', admin: admin })
military = GameCategory.create!({ name: 'Militar', admin: admin })
board_cards = GameCategory.create!({ name: 'Tabuleiro e Cartas', admin: admin })
sport_racing = GameCategory.create!({ name: 'Esporte e Corrida', admin: admin })
racing = GameCategory.create!({ name: 'Corrida', admin: admin })
team_sports = GameCategory.create!({ name: 'Esporte em Equipe', admin: admin })
sports = GameCategory.create!({ name: 'Esportes', admin: admin })
individual_sports = GameCategory.create!({ name: 'Esportes Individuais', admin: admin })
fishing_hunting = GameCategory.create!({ name: 'Pescaria e Caça', admin: admin })
sports_simulator = GameCategory.create!({ name: 'Simuladores de Esporte', admin: admin })
racing_simulator = GameCategory.create!({ name: 'Simulação de Corrida', admin: admin })
anime = GameCategory.create!({ name: 'Anime', admin: admin })
space = GameCategory.create!({ name: 'Espaciais', admin: admin })
sci_fi_cyberpunk = GameCategory.create!({ name: 'Ficção científica e cyberpunk', admin: admin })
mistery_detective = GameCategory.create!({ name: 'Mistério e detetive', admin: admin })
open_world = GameCategory.create!({ name: 'Mundo Aberto', admin: admin })
survival = GameCategory.create!({ name: 'Sobrevivência', admin: admin })
horror = GameCategory.create!({ name: 'Terror', admin: admin })
online_competitive = GameCategory.create!({ name: 'Competitivo Online', admin: admin })
coop = GameCategory.create!({ name: 'Cooperativo', admin: admin })
mmo = GameCategory.create!({ name: 'MMO', admin: admin })
multiplayer = GameCategory.create!({ name: 'Multijogador', admin: admin })
local_party_multiplayer = GameCategory.create!({ name: 'Multijogador Local e em Grupo', admin: admin })
local_network = GameCategory.create!({ name: 'Rede Local (LAN)', admin: admin })
singleplayer = GameCategory.create!({ name: 'Um Jogador', admin: admin })
game_category = FactoryBot.create(:game_category, admin: admin2, created_at: 60.days.ago)
game_category2 = FactoryBot.create(:game_category, admin: admin2, created_at: 59.days.ago)
game_category3 = FactoryBot.create(:game_category, admin: admin2, created_at: 58.days.ago)
game_category4 = FactoryBot.create(:game_category, admin: admin2, created_at: 57.days.ago)
game_category5 = FactoryBot.create(:game_category, admin: admin2, created_at: 56.days.ago)
game_category6 = FactoryBot.create(:game_category, admin: admin2, created_at: 55.days.ago)
